<a href="https://colab.research.google.com/github/Poojitha-d/CODES/blob/main/Copy_of_Welcome_To_Colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
#2
import pandas as pd
import numpy as np
data = [15,22,29,21,15,24,32,21,15,30]
mean = np.mean(data)
median = np.median(data)
variance = np.var(data)
std_dev = np.std(data)
mode = pd.Series(data).mode()
print("Mean:", mean)
print("Median:", median)
print("variance:",variance)
print("Standard Deviation:", std_dev)
print("Mode:", mode)


Mean: 22.4
Median: 21.5
variance: 36.44
Standard Deviation: 6.036555309114628
Mode: 0    15
dtype: int64


In [5]:
#4
name = "priya"
age = 10
height = 5.6
is_active = True
print(f"Name:{name},Age:{age},Height:{height}m,Active:{is_active}")

Name:priya,Age:10,Height:5.6m,Active:True


In [6]:
#5
a=int(input("Enter a number: "))
if a>0:
  print(a,"is a positive number.")
else:
  print(a,"is a negative number.")

Enter a number: -13
-13 is a negative number.


In [ ]:
#6
a = int(input("Enter a number : "))
for i in range (1,11):
  print(a,"x",i,"=",a*i)

Enter a number : 4
4 x 1 = 4
4 x 2 = 8
4 x 3 = 12
4 x 4 = 16
4 x 5 = 20
4 x 6 = 24
4 x 7 = 28
4 x 8 = 32
4 x 9 = 36
4 x 10 = 40


In [ ]:
#7
fruits = ["Mango","Cherry","Orange","Banana","Apple"]
print("First fruit:", fruits[0])
fruits.append("Strawberry")
print("List after appending a fruit:",fruits)
fruits.remove("Orange")
print("List after removing Banana:",fruits)
fruits.sort()
print("List after sorting:",fruits)
print("Length of the list:",len(fruits))


First fruit: Mango
List after appending a fruit: ['Mango', 'Cherry', 'Orange', 'Banana', 'Apple', 'Strawberry']
List after removing Banana: ['Mango', 'Cherry', 'Banana', 'Apple', 'Strawberry']
List after sorting: ['Apple', 'Banana', 'Cherry', 'Mango', 'Strawberry']
Length of the list: 5


In [ ]:
#8
numbers = (15, 20, 5, 10, 25)
print("Element at index 2", numbers [2])
count_5 = numbers.count(15)
print("Count of 15 in the tuple:",count_5)
index_of_10 = numbers.index(10)
print("Index of 10 in the tuples", index_of_10)
print("Length of the tuple:", len(numbers))
sliced_tuple = numbers [1:4]
print("Sliced portion of the tuple (from index 1 to 3):", sliced_tuple)

Element at index 2 5
Count of 15 in the tuple: 1
Index of 10 in the tuples 3
Length of the tuple: 5
Sliced portion of the tuple (from index 1 to 3): (20, 5, 10)


In [ ]:
#9
students_marks = {"Ammu": 85, "Bunny": 92, "Chay": 78}
print("Marks of Bunny:",students_marks["Bunny"])
students_marks ["Dora"]= 88
print("Dictionary after adding Dora:", students_marks)
students_marks ["Ammu"]= 90
del students_marks["Chay"]
print("Dictionary after removing Chay:", students_marks)
if "Bunny" in students_marks:
 print("Bunny is in the dictionary.")
else:
 print("Bunny is not in the dictionary.")
print("Number of students:", len(students_marks))

Marks of Bunny: 92
Dictionary after adding Dora: {'Ammu': 85, 'Bunny': 92, 'Chay': 78, 'Dora': 88}
Dictionary after removing Chay: {'Ammu': 90, 'Bunny': 92, 'Dora': 88}
Bunny is in the dictionary.
Number of students: 3


In [7]:
#10
set1 = {1, 2, 3, 4, 5}
set2 = {4, 5, 6, 7, 8}

print("Set 1:", set1)
print("Set 2:", set2)

print("Union:", set1 | set2)
print("Intersection:", set1 & set2)
print("Difference (Set1 - Set2):", set1 - set2)
print("Symmetric Difference:", set1 ^ set2)


Set 1: {1, 2, 3, 4, 5}
Set 2: {4, 5, 6, 7, 8}
Union: {1, 2, 3, 4, 5, 6, 7, 8}
Intersection: {4, 5}
Difference (Set1 - Set2): {1, 2, 3}
Symmetric Difference: {1, 2, 3, 6, 7, 8}


In [ ]:
#11
def find_largest(numbers):
    return max(numbers)

sample_list = [12, 45, 78, 23, 89, 56]
print("Largest number:", find_largest(sample_list))


Largest number: 89


In [ ]:
#12
squares = [x**2 for x in range(1, 21) if x % 2 == 0]
print(squares)


[4, 16, 36, 64, 100, 144, 196, 256, 324, 400]


In [ ]:
#13
product = lambda x, y: x * y

a = int(input("Enter first number: "))
b = int(input("Enter second number: "))

print("Product:", product(a, b))


Enter first number: 3
Enter second number: 5
Product: 15


In [ ]:
#14
import numpy as np

arr1D = np.array([1, 2, 3, 4, 5])
print(arr1D)
print(arr1D.shape)
print(arr1D.ndim)

arr2D = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2D)
print(arr2D.shape)
print(arr2D.ndim)

arr3D = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(arr3D)
print(arr3D.shape)
print(arr3D.ndim)


[1 2 3 4 5]
(5,)
1
[[1 2 3]
 [4 5 6]]
(2, 3)
2
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
(2, 2, 2)
3


In [ ]:
#15
import numpy as np

array = np.random.randint(0, 100, size=(5, 5))
print("Generated 5x5 NumPy Array of Random Integers:")
print(array)

element = array[1, 2]
print("\nElement at row 2, column 3:", element)

third_row = array[2]
print("\n3rd Row of the Array:", third_row)

fourth_column = array[:, 3]
print("\n4th Column of the Array:", fourth_column)

subarray = array[1:3, 2:4]
print("\nSubarray (rows 1 to 2 and columns 2 to 3):")
print(subarray)

last_row = array[-1]
print("\nLast Row of the Array:", last_row)

last_column = array[:, -1]
print("Last Column of the Array:", last_column)


Generated 5x5 NumPy Array of Random Integers:
[[53  0 13 19 11]
 [45 87 35 10 84]
 [52 80 82 10 42]
 [35 33 25 62 17]
 [88 52 81 86 69]]

Element at row 2, column 3: 35

3rd Row of the Array: [52 80 82 10 42]

4th Column of the Array: [19 10 10 62 86]

Subarray (rows 1 to 2 and columns 2 to 3):
[[35 10]
 [82 10]]

Last Row of the Array: [88 52 81 86 69]
Last Column of the Array: [11 84 42 17 69]


In [ ]:
#16
import numpy as np

array = np.arange(1, 17).reshape(4, 4)
print("Generated 4x4 NumPy Array:")
print(array)
# Extracting sliced array
center_subarray = array[1:3, 1:3]
print("\nCenter 2x2 Subarray:")
print(center_subarray)

# Extracting diagonal elements
diagonal_elements = array.diagonal()
print("\nDiagonal Elements:")
print(diagonal_elements)


Generated 4x4 NumPy Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Center 2x2 Subarray:
[[ 6  7]
 [10 11]]

Diagonal Elements:
[ 1  6 11 16]


In [ ]:
#17
import numpy as np

array_2D = np.arange(1, 13).reshape(6, 2)
print(array_2D)

array_3D = array_2D.reshape(2, 3, 2)
print(array_3D)

flattened_array = array_3D.flatten()
print(flattened_array)



[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [ ]:
#18
import numpy as np

array_2D = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
array_1D = np.array([10, 20, 30])

result = array_2D + array_1D
print(array_2D)
print(array_1D)
print(result)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[10 20 30]
[[11 22 33]
 [14 25 36]
 [17 28 39]]


In [ ]:
#19
import numpy as np

A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])

addition = A + B
subtraction = A - B
multiplication = A * B
division = A / B

print(addition)
print(subtraction)
print(multiplication)
print(division)


[[10 10 10]
 [10 10 10]
 [10 10 10]]
[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]
[[ 9 16 21]
 [24 25 24]
 [21 16  9]]
[[0.11111111 0.25       0.42857143]
 [0.66666667 1.         1.5       ]
 [2.33333333 4.         9.        ]]


In [ ]:
#20
import pandas as pd

data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Math': [85, 78, 92],
    'Science': [88, 74, 95],
    'English': [90, 82, 88]
}

df = pd.DataFrame(data)
df['Total'] = df[['Math', 'Science', 'English']].sum(axis=1)

df['Grade'] = df['Total'].apply(lambda x: 'A' if x >= 250 else ('B' if x >= 200 else 'C'))

print(df)


      Name  Math  Science  English  Total Grade
0    Alice    85       88       90    263     A
1      Bob    78       74       82    234     B
2  Charlie    92       95       88    275     A
